{
  imports = [
    ./eduroam.nix
    ./feh.nix
    ./fonts.nix
    ./hypridle.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./hyprpaper.nix
    ./kitty.nix
    ./nixvim.nix
    ./openshot.nix
    ./rofi.nix
    ./shotcut.nix
    ./sioyek.nix
    ./waybar.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
